### ISSUE TITLE
Compatibility issues with Mujoco >= 3.0

### ISSUE THREAD

**Issue by rbharadwaj9** [srl-ethz/faive_gym_oss#9]
Between MuJoCo 2.3.7 and 3.0.0 based on the changelog: https://mujoco.readthedocs.io/en/latest/changelog.html#id40 number 11 of the breaking API changes, 
> For models which have `<option collision="all"/>`, delete the attribute.

This attribute needs to be removed from the MJCF XML files in order for the files to work with the latest simulator

**Comment by Yasu31** [comment]
just for linking to the PR that fixes this: https://github.com/srl-ethz/faive_gym_oss/pull/10
